DEP-1789 modify type AppCompatActivity to Activity
trustly/TrustlyAndroidSdk pull request #10
Opened 2024-08-05 12:32 UTC by marinakinalone

2024-08-14 12:30 UTC, marinakinalone commented
@jennylarsson94 I tested by adding the modification on the local SDK files in the native test app and it works!

2024-08-14 13:25 UTC, jennylarsson94 commented
> @jennylarsson94 I tested by adding the modification on the local SDK files in the native test app and it works!

Good! Don't forget to add the changes to the `Changelog.md` file as well

2024-08-15 11:59 UTC, jennylarsson94 requested changes

2024-08-15 11:59 UTC, jennylarsson94 commented on Changelog.md
> +- **Appcompat**: Removed.
This should be moved to a new section - look at the structure of the changelog

2024-08-15 11:59 UTC, jennylarsson94 commented on .vscode/settings.json
Add a gitignore on this one

2024-08-15 13:08 UTC, jennylarsson94 approved these changes

2024-08-15 13:10 UTC, merged