feat:new API replacing delegate pattern with lambdas.
trustly/TrustlyAndroidSdk pull request #8
Opened 2023-03-22 13:51 UTC by daniela-trustly

2023-03-23 14:14 UTC, michaellindblom requested changes
Are you sure all commits have been pushed because I can't compile the code; enums are missing in `TrustlyJavascriptInterface` and missing one parentheses as can see in two of my comments.


Also, not related to your PR but we should probably bump the `minSdkVersion 19` since the function `getUrl()` in `TrustlyWebChromeClient` requires api version 21 (Android 5). So here:
`customTab.launchUrl(view.getContext(), request.getUrl());`

2023-03-23 14:14 UTC, michaellindblom commented on README.md
> +In case no custom functionality is provided, the webview will load the `SuccessURL`, in case of a success event, or the `FailURL` in case of a error or an abort event.
Small thing but remove the comma ',' after `SuccessURL`. I stumbled on the sentence otherwise :)

So should be:

> In case no custom functionality is provided, the webview will load the `SuccessURL` in case of a success event, or the `FailURL` in case of a error or an abort event.

2023-03-23 14:14 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
>    }
Small thing but just to be consistent, maybe this is better (`Activity activity` instead of `Activity a`)?

```
public TrustlyJavascriptInterface(Activity activity, TrustlyWebView webViewHandler) {
        this.activity = activity;
        this.webViewHandler = webViewHandler;
    }
```

2023-03-23 14:14 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +  TrustlyWebView webViewHandler;
I think `activity` and `webViewHandler` can both be private

2023-03-23 14:14 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +        throw new UnsupportedOperationException(String.format("Unsupported event type: %s", type);
Missing `)` in the end. Should be:

`throw new UnsupportedOperationException(String.format("Unsupported event type: %s", type));`

2023-03-23 14:14 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
>        case ERROR:
I cant find the enums for these switch cases. They did exists in the deleted file `TrustlySDKEventObject.java`

```
public enum TrustlyEventType {
    SUCCESS("onTrustlyCheckoutSuccess"),
    REDIRECT("onTrustlyCheckoutRedirect"),
    ABORT("onTrustlyCheckoutAbort"),
    ERROR("onTrustlyCheckoutError");
```

2023-03-24 09:28 UTC, michaellindblom requested changes
I see now that the Google Play requires `targetSdkVersion` to be at least 31, so I think it can be a good practice to update to 31, `compileSdkVersion` also need to be updated to 31.

2023-03-24 09:28 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +                    this.webViewHandler.errorHandler.onTrustlyCheckoutError();
`this` keyword not needed, removing it I think will make the code look cleaner

2023-03-24 09:28 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +    void handleRedirect(String URLString) {
`handleRedirect` can be private

2023-03-24 09:28 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +    private TrustlyWebView webViewHandler;
These can be `private final`

2023-03-24 09:28 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyWebView.java
>            new LayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)));
`this` keyword not needed.

2023-03-24 09:28 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyWebView.java
A bit further down I see the method `configWebSettings(WebView mainView)` 

this method needs no parameter since `this` is the WebView that is passed to the method, the class extends the WebView that is passed so "this" can be accessed directly from the `configWebSettings()` method without being passed.

So the method can look like this:

```
private void configWebSettings() throws WebSettingsException {
        try {
            WebSettings webSettings = getSettings();
            webSettings.setJavaScriptEnabled(true);
            webSettings.setDomStorageEnabled(true);
            webSettings.setJavaScriptCanOpenWindowsAutomatically(true);
            webSettings.setSupportMultipleWindows(true);
        } catch (Exception e) {
            throw new WebSettingsException(e.getMessage());
        }
    }
```

2023-03-24 20:44 UTC, michaellindblom requested changes

2023-03-24 20:44 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyWebView.java
>        this.setLayoutParams(
Still some `this` that can be removed :)

Can look like below:

```
 private void tryOpeningUrlInWebView(AppCompatActivity activity, String url) {
    try {
      // Enable javascript and DOM Storage
      configWebSettings();

      setWebViewClient(new WebViewClient());
      setWebChromeClient(new TrustlyWebChromeClient());
      addJavascriptInterface(new TrustlyJavascriptInterface(activity, this), TrustlyJavascriptInterface.NAME);

      setLayoutParams(
          new LayoutParams(new ViewGroup.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)));

      loadUrl(url);
    } catch (WebSettingsException e) {
      Log.d("WebView", "configWebView: Could not config WebSettings");
    } catch (Exception e) {
      Log.d("WebView", "configWebView: Unknown Problem happened");
    }
  }
```

2023-03-24 20:44 UTC, michaellindblom commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +    public void handleTrustlyEvent(String typeLabel, String url, String packageName) {
Just saw that `packageName` does not seem to be used

2023-03-28 07:29 UTC, daniela-trustly commented on TrustlyAndroidSdk/Trustly-Android-Library/src/main/java/com/trustlyAndroidLibrary/TrustlyJavascriptInterface.java
> +    public void handleTrustlyEvent(String typeLabel, String url, String packageName) {
This method is defined like this in the react counterpart, so I can't change it without implementing and deploying a change there (which is out of scope now). Java doesn't seem to have a very straightforward way of marking params as unused so I'll leave it as is

2023-03-28 07:30 UTC, daniela-trustly commented
Thanks for the review @michaellindblom 
I'll go ahead an merge this PR as it's been through enough rounds of review and there's other work pending on this PR getting merged, so I'd want to unblock the rest of the work.
If you feel like there is something that needs to be updated, feel free to open a PR

2023-03-28 07:30 UTC, merged